"""baseline: schema as of spec 62

Revision ID: 6fc935931248
Revises:
Create Date: 2026-09-30 00:51:16.318707

This is the FIRST Alembic revision this repo has ever had. It was generated
with `alembic revision --autogenerate` against a fresh, empty Postgres 16
database and verified with `alembic check` (no diff) — it's an exact,
tool-generated snapshot of models/db.py as of spec §62, not a hand-written
reconstruction, and every table it creates is one the 10 hand-rolled
migrate_*.py scripts had already built up incrementally in production.

Production already has this schema (via those scripts + Base.metadata.
create_all()'s missing-table creation at every app startup) — do NOT run
`alembic upgrade head` against it, which would try to CREATE TABLE on
tables that already exist and fail. Instead, tell Alembic production is
already here without touching the database:

    cd app && alembic stamp head

From that point on, every schema change goes through
`alembic revision --autogenerate -m "..."` + a real deploy-time
`alembic upgrade head` — not a new migrate_*.py script. The old scripts
stay in the repo as history; nothing here retroactively changes what they
already did.

A fresh install (a new deployment with no existing database at all) runs
`alembic upgrade head` normally, same as any other Alembic project — it's
only the one already-migrated production database that needs `stamp`
instead of `upgrade`.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fc935931248'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discord_servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('guild_id', sa.Text(), nullable=False),
    sa.Column('bot_token', sa.Text(), nullable=True),
    sa.Column('public_key', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id')
    )
    op.create_table('kingdoms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('public_site_title', sa.Text(), nullable=True),
    sa.Column('admin_console_title', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discord_id', sa.Text(), nullable=False),
    sa.Column('discord_username', sa.Text(), nullable=False),
    sa.Column('is_superadmin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('discord_id')
    )
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kingdom_id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('color', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('icon_image_data', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['kingdom_id'], ['kingdoms.id'], ),
    sa.ForeignKeyConstraint(['server_id'], ['discord_servers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('user_kingdoms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kingdom_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['kingdom_id'], ['kingdoms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'kingdom_id', name='uq_user_kingdom')
    )
    op.create_table('announcement_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owning_tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('title_template', sa.Text(), nullable=False),
    sa.Column('body_template', sa.Text(), nullable=False),
    sa.Column('leadership_only', sa.Boolean(), nullable=False),
    sa.Column('event_offset_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['owning_tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owning_tenant_id', 'name', name='uq_announcement_template_name')
    )
    op.create_table('announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owning_tenant_id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body_markdown', sa.Text(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('leadership_only', sa.Boolean(), nullable=False),
    sa.Column('recurring', sa.Boolean(), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('event_offset_minutes', sa.Integer(), nullable=False),
    sa.CheckConstraint("scope IN ('alliance', 'kingdom-wide')", name='ck_announcement_scope_valid'),
    sa.CheckConstraint("status IN ('draft', 'scheduled', 'posted', 'failed', 'cancelled')", name='ck_announcement_status'),
    sa.CheckConstraint('NOT recurring OR interval_days > 0', name='ck_announcement_interval_positive_if_recurring'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owning_tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('table_name', sa.Text(), nullable=False),
    sa.Column('row_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('before', sa.Text(), nullable=True),
    sa.Column('after', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("action IN ('create', 'update', 'delete')", name='ck_audit_action'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owning_tenant_id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.Column('start_time_utc', sa.Time(), nullable=False),
    sa.Column('duration_hours', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('discord_channel', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('leadership_only', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('anchor_date', sa.Date(), nullable=False),
    sa.Column('notification_channel_id', sa.Text(), nullable=False),
    sa.Column('notification_role_id', sa.Text(), nullable=False),
    sa.Column('notify_minutes_before', sa.Integer(), nullable=True),
    sa.Column('cover_image_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("scope IN ('alliance', 'kingdom-wide')", name='ck_scope_valid'),
    sa.CheckConstraint('duration_hours > 0', name='ck_duration_positive'),
    sa.CheckConstraint('interval_days > 0', name='ck_interval_positive'),
    sa.ForeignKeyConstraint(['owning_tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('kingdom_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_by', sa.Integer(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("role IN ('owner', 'coordinator', 'viewer', 'kingdom_coordinator')", name='ck_invite_role'),
    sa.CheckConstraint('(tenant_id IS NOT NULL AND kingdom_id IS NULL) OR (tenant_id IS NULL AND kingdom_id IS NOT NULL)', name='ck_invite_exactly_one_target'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['kingdom_id'], ['kingdoms.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['used_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('scheduler_state',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('job_name', sa.Text(), nullable=False),
    sa.Column('last_run_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_result', sa.Text(), nullable=True),
    sa.Column('last_detail', sa.Text(), nullable=True),
    sa.Column('next_run_utc', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('tenant_id', 'job_name')
    )
    op.create_table('user_tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("role IN ('owner', 'coordinator', 'viewer')", name='ck_user_tenant_role'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tenant_id', name='uq_user_tenant')
    )
    op.create_table('announcement_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('announcement_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('discord_channel_id', sa.Text(), nullable=False),
    sa.Column('discord_message_id', sa.Text(), nullable=True),
    sa.Column('post_status', sa.Text(), nullable=False),
    sa.Column('status_detail', sa.Text(), nullable=True),
    sa.CheckConstraint("post_status IN ('pending', 'posted', 'error')", name='ck_announcement_target_status'),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('announcement_id', 'tenant_id', name='uq_announcement_target')
    )
    op.create_table('event_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('notification_channel_id', sa.Text(), nullable=False),
    sa.Column('notification_role_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event_definitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'tenant_id', name='uq_event_target')
    )
    op.create_table('event_tenant_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('notification_channel_id', sa.Text(), nullable=False),
    sa.Column('notification_role_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event_definitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'tenant_id', name='uq_event_tenant_notification')
    )
    op.create_table('occurrences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('occurrence_date', sa.Date(), nullable=False),
    sa.Column('start_datetime_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_datetime_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('post_to_discord', sa.Boolean(), nullable=False),
    sa.Column('post_status', sa.Text(), nullable=False),
    sa.Column('status_detail', sa.Text(), nullable=True),
    sa.Column('reminder_sent', sa.Boolean(), nullable=False),
    sa.Column('window_generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event_definitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'occurrence_date', name='uq_occurrence')
    )
    op.create_table('post_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('event_name', sa.Text(), nullable=False),
    sa.Column('occurrence_date', sa.Date(), nullable=False),
    sa.Column('discord_event_id', sa.Text(), nullable=True),
    sa.Column('discord_guild_id', sa.Text(), nullable=False),
    sa.Column('posted_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('posted_by', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('status_detail', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event_definitions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'event_name', 'occurrence_date', name='uq_post_log')
    )
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('error_type', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('related_occurrence_id', sa.Integer(), nullable=True),
    sa.Column('related_announcement_id', sa.Integer(), nullable=True),
    sa.Column('submitter_contact', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('upvote_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("kind IN ('feedback', 'event_request', 'announcement_request', 'error')", name='ck_ticket_kind'),
    sa.CheckConstraint("status IN ('open', 'planned', 'in_progress', 'done', 'declined')", name='ck_ticket_status'),
    sa.CheckConstraint('related_occurrence_id IS NULL OR related_announcement_id IS NULL', name='ck_ticket_related_mutually_exclusive'),
    sa.ForeignKeyConstraint(['related_announcement_id'], ['announcements.id'], ),
    sa.ForeignKeyConstraint(['related_occurrence_id'], ['occurrences.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('voter_key', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_id', 'voter_key', name='uq_ticket_vote')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_votes')
    op.drop_table('tickets')
    op.drop_table('post_log')
    op.drop_table('occurrences')
    op.drop_table('event_tenant_notifications')
    op.drop_table('event_targets')
    op.drop_table('announcement_targets')
    op.drop_table('user_tenants')
    op.drop_table('scheduler_state')
    op.drop_table('invites')
    op.drop_table('event_definitions')
    op.drop_table('audit_log')
    op.drop_table('announcements')
    op.drop_table('announcement_templates')
    op.drop_table('user_kingdoms')
    op.drop_table('tenants')
    op.drop_table('users')
    op.drop_table('kingdoms')
    op.drop_table('discord_servers')
    # ### end Alembic commands ###
